// Generated by `cargo xtask bridgegen` from src/molecules/accordion_item.rs:17. Do not edit.

import type { ReactNode } from 'react';

export interface AccordionItemProps {
  /** `AttrValue` — src/molecules/accordion_item.rs:10 */
  title: string;
  /** `Children` — src/molecules/accordion_item.rs:11 */
  children: ReactNode;
  /** `bool` — src/molecules/accordion_item.rs:13; `#[prop_or_default]` */
  open?: boolean;
}

export function AccordionItem($props: AccordionItemProps) {
  const props = {
    ...$props,
    open: $props.open ?? false,
  };
  return (
    <details className="card-accordeon" open={props.open}>
      <summary className="card-accordeon-header">
        <div className="card-accordeon-header-inner">
          <div className="card-accordeon-title-container">
            <h3 className="card-accordeon-title">
              {props.title}
            </h3>
          </div>
        </div>
        <div aria-hidden="true" className="card-accordeon-arrow">
          ▾
        </div>
      </summary>
      <div className="card-accordeon-content">
        {props.children}
      </div>
    </details>
  );
}
