// Generated by `cargo xtask bridgegen` from src/atoms/badge_num.rs:11. Do not edit.

export interface BadgeNumProps {
  /** `AttrValue` — src/atoms/badge_num.rs:7 */
  number: string;
}

export function BadgeNum(props: BadgeNumProps) {
  return (
    <div className="badge-num">
      {props.number}
    </div>
  );
}
