// Generated by `cargo xtask bridgegen` from src/molecules/bg_check_item.rs:16. Do not edit.

export interface BgCheckItemProps {
  /** `AttrValue` — src/molecules/bg_check_item.rs:6 */
  label: string;
  /** `AttrValue` — src/molecules/bg_check_item.rs:7 */
  background: string;
  /** `AttrValue` — src/molecules/bg_check_item.rs:8 */
  color: string;
  /** `AttrValue` — src/molecules/bg_check_item.rs:10 */
  icon: string;
  /** `Option<AttrValue>` — src/molecules/bg_check_item.rs:12; `#[prop_or_default]`, so `None` */
  border?: string | undefined;
}

export function BgCheckItem(props: BgCheckItemProps) {
  return (
    <div style={{ "background": props.background, "color": props.color, ...(props.border != null ? { "border": props.border } : {}) }} className="bg-check">
      <span className="ic">
        {props.icon}
      </span>
      {props.label}
    </div>
  );
}
