// Generated by `cargo xtask bridgegen` from src/atoms/button.rs:30. Do not edit.

export interface ButtonProps {
  /** `AttrValue` — src/atoms/button.rs:21 */
  label: string;
  /** `ButtonVariant` — src/atoms/button.rs:23; `#[prop_or(ButtonVariant::Primary)]` */
  variant?: 'primary' | 'ghost';
  /** `Option<AttrValue>` — src/atoms/button.rs:26; `#[prop_or_default]`, so `None` */
  href?: string | undefined;
}

export function Button($props: ButtonProps) {
  const props = {
    ...$props,
    variant: $props.variant ?? 'primary',
  };
  return (
    props.href != null ? (
      <a href={props.href} className={props.variant === "ghost" ? "btn btn-ghost" : "btn btn-primary"}>
        {props.label}
      </a>
    ) : (
      <button type="button" className={props.variant === "ghost" ? "btn btn-ghost" : "btn btn-primary"}>
        {props.label}
      </button>
    )
  );
}
