// Generated by `cargo xtask bridgegen` from src/molecules/callout.rs:13. Do not edit.

export interface CalloutProps {
  /** `AttrValue` — src/molecules/callout.rs:7 */
  label: string;
  /** `AttrValue` — src/molecules/callout.rs:8 */
  french: string;
  /** `AttrValue` — src/molecules/callout.rs:9 */
  english: string;
}

export function Callout(props: CalloutProps) {
  return (
    <div className="callout">
      <b>
        {props.label}
      </b>
      {" "}
      <span className="fr">
        {props.french}
      </span>
      {" "}
      {props.english}
    </div>
  );
}
