// Generated by `cargo xtask bridgegen` from src/molecules/case_card.rs:15. Do not edit.

export interface CaseCardProps {
  /** `AttrValue` — src/molecules/case_card.rs:9 */
  href: string;
  /** `AttrValue` — src/molecules/case_card.rs:10 */
  tag: string;
  /** `AttrValue` — src/molecules/case_card.rs:11 */
  title: string;
}

export function CaseCard(props: CaseCardProps) {
  return (
    <article className="case-card">
      <a href={props.href} className="case-card__link">
        <div className="case-card__image">
          <span className="tag-label tag-label-blue">
            {props.tag}
          </span>
          16:9 image
        </div>
        <div className="case-card__content">
          <h3 className="case-card__title">
            {props.title}
          </h3>
        </div>
      </a>
    </article>
  );
}
