// Generated by `cargo xtask bridgegen` from src/atoms/code_block.rs:27. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `language` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/atoms/code_block.rs:19
// Note: [sentinel-integrity] cell copyable_true (primary): the sentinel for `language` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/atoms/code_block.rs:19

export interface CodeBlockProps {
  /** `AttrValue` — src/atoms/code_block.rs:13 */
  code: string;
  /** `AttrValue` — src/atoms/code_block.rs:19; `#[prop_or(AttrValue::Static("rust"))]` */
  language?: string;
  /** `bool` — src/atoms/code_block.rs:23; `#[prop_or(true)]` */
  copyable?: boolean;
}

export function CodeBlock($props: CodeBlockProps) {
  const props = {
    ...$props,
    language: $props.language ?? 'rust',
    copyable: $props.copyable ?? true,
  };
  return (
    <div className="code-block">
      <div className="code-block-bar">
        <span className="code-block-lang">
          {props.language}
        </span>
        {props.copyable && (
          <button type="button" aria-label="Copy this snippet" className="code-block-copy">
            Copy
          </button>
        )}
      </div>
      <pre className="code-block-pre">
        <code className={`language-${props.language}`}>
          {props.code}
        </code>
      </pre>
    </div>
  );
}
