// Generated by `cargo xtask bridgegen` from src/molecules/dataset_card.rs:57. Do not edit.
// Note: [sentinel-integrity] cell thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell publisher_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__publisher_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__publisher_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__publisher_some__thumbnail_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell publisher_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__publisher_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__publisher_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__publisher_some__thumbnail_some__badge_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell publisher_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__publisher_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell version_some__publisher_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell description_some__version_some__publisher_some__thumbnail_some__badge_some__badge_class_some (primary): the sentinel for `initial` (\u{E000}1\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `initial` in this cell — src/molecules/dataset_card.rs:32
// Note: [sentinel-integrity] cell badge_class_some (primary): the sentinel for `badge_class` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `badge_class` in this cell — src/molecules/dataset_card.rs:51

export interface DatasetCardProps {
  /** `AttrValue` — src/molecules/dataset_card.rs:26 */
  title: string;
  /** `AttrValue` — src/molecules/dataset_card.rs:32 */
  initial: string;
  /** `AttrValue` — src/molecules/dataset_card.rs:34 */
  href: string;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:36; `#[prop_or_default]`, so `None` */
  description?: string | undefined;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:40; `#[prop_or_default]`, so `None` */
  version?: string | undefined;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:42; `#[prop_or_default]`, so `None` */
  publisher?: string | undefined;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:45; `#[prop_or_default]`, so `None` */
  thumbnail?: string | undefined;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:48; `#[prop_or_default]`, so `None` */
  badge?: string | undefined;
  /** `Option<AttrValue>` — src/molecules/dataset_card.rs:51; `#[prop_or_default]`, so `None` */
  badgeClass?: string | undefined;
  /** `AttrValue` — src/molecules/dataset_card.rs:53; `#[prop_or(AttrValue::Static("View documentation"))]` */
  actionLabel?: string;
}

export function DatasetCard($props: DatasetCardProps) {
  const props = {
    ...$props,
    actionLabel: $props.actionLabel ?? 'View documentation',
  };
  return (
    <a href={props.href} className="dataset-card">
      <div className="dataset-card__media">
        {props.thumbnail != null ? (
          <img src={props.thumbnail} alt="" loading="lazy" className="dataset-card__thumb" />
        ) : (
          <span aria-hidden="true" className="dataset-card__thumb dataset-card__thumb--empty">
            {props.initial}
          </span>
        )}
        {props.badge != null && (
          <span className={props.badgeClass != null ? `dataset-card__badge ${props.badgeClass}` : "dataset-card__badge"}>
            {props.badge}
          </span>
        )}
      </div>
      <div className="dataset-card__body">
        <h3 className="dataset-card__title">
          {props.title}
          {props.version != null && (
            <span className="dataset-card__version">
              {props.version}
            </span>
          )}
        </h3>
        {props.publisher != null && (
          <p className="dataset-card__publisher">
            {props.publisher}
          </p>
        )}
        {props.description != null && (
          <p className="dataset-card__description">
            {props.description}
          </p>
        )}
        <span className="dataset-card__action">
          {props.actionLabel}
        </span>
      </div>
    </a>
  );
}
