// Generated by `cargo xtask bridgegen` from src/molecules/decl_card.rs:17. Do not edit.

export interface DeclCardProps {
  /** `AttrValue` — src/molecules/decl_card.rs:8 */
  category: string;
  /** `AttrValue` — src/molecules/decl_card.rs:9 */
  src: string;
  /** `AttrValue` — src/molecules/decl_card.rs:10 */
  alt: string;
  /** `AttrValue` — src/molecules/decl_card.rs:11 */
  declType: string;
  /** `AttrValue` — src/molecules/decl_card.rs:12 */
  title: string;
  /** `AttrValue` — src/molecules/decl_card.rs:13 */
  description: string;
}

export function DeclCard(props: DeclCardProps) {
  return (
    <figure data-cat={props.category} className="decl-card">
      <img src={props.src} loading="lazy" alt={props.alt} />
      <div className="decl-body">
        <span className="decl-type">
          {props.declType}
        </span>
        <div className="decl-title">
          {props.title}
        </div>
        <div className="decl-desc">
          {props.description}
        </div>
      </div>
    </figure>
  );
}
