// Generated by `cargo xtask bridgegen` from src/atoms/evolution_badge.rs:23. Do not edit.

export interface EvolutionBadgeProps {
  /** `AttrValue` — src/atoms/evolution_badge.rs:18 */
  value: string;
  /** `Trend` — src/atoms/evolution_badge.rs:19 */
  trend: 'up' | 'down' | 'flat';
}

export function EvolutionBadge(props: EvolutionBadgeProps) {
  return (
    <span className={props.trend === "down" ? "evolution-badge evolution-badge--down" : props.trend === "flat" ? "evolution-badge evolution-badge--flat" : "evolution-badge evolution-badge--up"}>
      <span aria-hidden="true" className="evolution-badge__glyph">
        {props.trend === "down" ? "▼" : props.trend === "flat" ? "–" : "▲"}
      </span>
      <span className="sr-only">
        {props.trend === "down" ? "down" : props.trend === "flat" ? "unchanged" : "up"}
      </span>
      <span className="evolution-badge__value">
        {props.value}
      </span>
    </span>
  );
}
