// Generated by `cargo xtask bridgegen` from src/organisms/hero_filter.rs:34. Do not edit.

import type { ReactNode } from 'react';

export interface HeroFilterProps {
  /** `AttrValue` — src/organisms/hero_filter.rs:25 */
  title: string;
  /** `AttrValue` — src/organisms/hero_filter.rs:26 */
  description: string;
  /** `Children` — src/organisms/hero_filter.rs:28 */
  children: ReactNode;
  /** `bool` — src/organisms/hero_filter.rs:30; `#[prop_or_default]` */
  withBackdrop?: boolean;
}

export function HeroFilter($props: HeroFilterProps) {
  const props = {
    ...$props,
    withBackdrop: $props.withBackdrop ?? false,
  };
  return (
    <section className={props.withBackdrop ? "hero-filter hero-filter--backdrop" : "hero-filter"}>
      {props.withBackdrop && (
        <div className="hero-filter__image">
          <div className="hero-filter__overlay" />
        </div>
      )}
      <div className="wrap hero-filter__container">
        <div className="hero-filter__content">
          <h1 className="hero-filter__title">
            {props.title}
          </h1>
          <p className="hero-filter__description">
            {props.description}
          </p>
        </div>
        <div className="hero-filter__actions">
          {props.children}
        </div>
      </div>
    </section>
  );
}
