// Generated by `cargo xtask bridgegen` from src/organisms/hero.rs:35. Do not edit.

import type { ReactNode } from 'react';

export interface HeroProps {
  /** `HeroVariant` — src/organisms/hero.rs:26 */
  variant: 'full' | 'compact';
  /** `AttrValue` — src/organisms/hero.rs:27 */
  eyebrow: string;
  /** `AttrValue` — src/organisms/hero.rs:28 */
  titleSuffix: string;
  /** `AttrValue` — src/organisms/hero.rs:29 */
  lede: string;
  /** `Children` — src/organisms/hero.rs:31 */
  children: ReactNode;
}

export function Hero(props: HeroProps) {
  return (
    <header className={props.variant === "compact" ? "libhero" : "hero"}>
      <div className="gold-stripe" />
      {props.variant === "compact" ? null : (
        <svg viewBox="0 0 1180 520" preserveAspectRatio="xMaxYMid slice" aria-hidden="true" className="mesh-bg">
          <circle cx="960" cy="140" r="150" fill="#BFD1FE" opacity=".14" />
          <circle cx="1080" cy="260" r="190" fill="#006EF0" opacity=".16" />
          <circle cx="880" cy="300" r="120" fill="#040553" opacity=".35" />
          <circle cx="1000" cy="380" r="90" fill="#B5C8F3" opacity=".12" />
          <circle cx="1140" cy="120" r="70" fill="#FFD047" opacity=".10" />
          <line x1="960" y1="140" x2="1080" y2="260" stroke="#BFD1FE" strokeOpacity=".25" strokeWidth="1" />
          <line x1="1080" y1="260" x2="880" y2="300" stroke="#BFD1FE" strokeOpacity=".25" strokeWidth="1" />
          <line x1="880" y1="300" x2="1000" y2="380" stroke="#BFD1FE" strokeOpacity=".2" strokeWidth="1" />
        </svg>
      )}
      <div className="wrap">
        <span className="hero-eyebrow">
          <span className="sw" />
          {" "}
          {props.eyebrow}
        </span>
        <h1>
          {"The "}
          <em>
            EONA-X
          </em>
          {" "}
          {props.titleSuffix}
        </h1>
        <p className="lede">
          {props.lede}
        </p>
        <div className="hero-actions">
          {props.children}
        </div>
      </div>
    </header>
  );
}
