// Generated by `cargo xtask bridgegen` from src/molecules/logo_download_card.rs:22. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `file` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/logo_download_card.rs:12
// Note: [sentinel-integrity] cell is_transparent_true (primary): the sentinel for `file` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/logo_download_card.rs:12

import type * as React from 'react';

export interface LogoDownloadCardProps {
  /** `AttrValue` — src/molecules/logo_download_card.rs:10 */
  label: string;
  /** `AttrValue` — src/molecules/logo_download_card.rs:12 */
  file: string;
  /** `AttrValue` — src/molecules/logo_download_card.rs:14 */
  downloadName: string;
  /** `AttrValue` — src/molecules/logo_download_card.rs:16; `#[prop_or_default]` */
  previewStyle?: string;
  /** `bool` — src/molecules/logo_download_card.rs:18; `#[prop_or_default]` */
  isTransparent?: boolean;
}

export function cssText(css: string | undefined): React.CSSProperties {
  const out: Record<string, string> = {};
  const s = css ?? "";
  let depth = 0;
  let quote = "";
  let start = 0;
  let colon = -1;
  const flush = (end: number) => {
    if (colon >= 0) {
      const raw = s.slice(start, colon).trim();
      if (raw) {
        const key = raw.startsWith("--")
          ? raw
          : raw.toLowerCase().replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
        out[key] = s.slice(colon + 1, end).trim();
      }
    }
    start = end + 1;
    colon = -1;
  };
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quote) {
      if (c === "\\" ) i++;
      else if (c === quote) quote = "";
    } else if (c === '"' || c === "'") {
      quote = c;
    } else if (c === "(") {
      depth++;
    } else if (c === ")") {
      if (depth > 0) depth--;
    } else if (depth === 0) {
      if (c === ":" && colon < 0) colon = i;
      else if (c === ";") flush(i);
    }
  }
  flush(s.length);
  return out as React.CSSProperties;
}

export function LogoDownloadCard($props: LogoDownloadCardProps) {
  const props = {
    ...$props,
    previewStyle: $props.previewStyle ?? '',
    isTransparent: $props.isTransparent ?? false,
  };
  return (
    <a href={props.file} download={props.downloadName} className="logo-download">
      <span style={cssText(props.previewStyle)} className={props.isTransparent ? "logo-download__preview is-transparent" : "logo-download__preview"}>
        <img src={props.file} alt="" loading="lazy" />
      </span>
      <span className="logo-download__label">
        {props.label}
      </span>
      <span className="logo-download__action">
        ↓ Download SVG
      </span>
    </a>
  );
}
