// Generated by `cargo xtask bridgegen` from src/organisms/main_nav.rs:26. Do not edit.

import type { NavLink } from './types';

export interface MainNavProps {
  /** `Option<NavLink>` — src/organisms/main_nav.rs:21; `#[prop_or_default]`, so `None` */
  back?: NavLink | undefined;
  /** `Vec<NavLink>` — src/organisms/main_nav.rs:22 */
  links: NavLink[];
}

export function MainNav(props: MainNavProps) {
  return (
    <nav className="mainnav">
      <div className="wrap">
        <div className="brandmark">
          <span className="dot" />
          {"  EONA-X"}
        </div>
        <div className="navlinks">
          {props.back != null && (
            <a href={props.back.href} className="back">
              {"← "}
              {props.back.label}
            </a>
          )}
          {props.links.map((item, i) => (
            <a key={i} href={item.href}>
              {item.label}
            </a>
          ))}
        </div>
        <div className="navspacer" />
        <div className="navutil">
          <a href="tokens.json">
            tokens.json
          </a>
          <a href="tokens.css">
            tokens.css
          </a>
        </div>
      </div>
    </nav>
  );
}
