// Generated by `cargo xtask bridgegen` from src/molecules/member_card.rs:11. Do not edit.

export interface MemberCardProps {
  /** `AttrValue` — src/molecules/member_card.rs:7 */
  name: string;
}

export function MemberCard(props: MemberCardProps) {
  return (
    <div className="member-card">
      <div className="member-card__logo">
        {props.name}
      </div>
    </div>
  );
}
