// Generated by `cargo xtask bridgegen` from src/molecules/member_filter_card.rs:18. Do not edit.

export interface MemberFilterCardProps {
  /** `AttrValue` — src/molecules/member_filter_card.rs:11 */
  name: string;
  /** `AttrValue` — src/molecules/member_filter_card.rs:12 */
  memberType: string;
  /** `AttrValue` — src/molecules/member_filter_card.rs:13 */
  country: string;
  /** `Vec<&'static str>` — src/molecules/member_filter_card.rs:14 */
  sectors: string[];
}

export function MemberFilterCard(props: MemberFilterCardProps) {
  return (
    <article className="card-member__filter">
      <div className="card-member__filter-header">
        <div className="card-member__filter-logo">
          logo
        </div>
        <div className="card-member__filter-title">
          <h3 className="card-member__filter-title-name">
            {props.name}
          </h3>
          <div className="card-member__filter-title-type">
            <p>
              {props.memberType}
            </p>
          </div>
        </div>
      </div>
      <div className="card-member__filter-localisation">
        <div className="term">
          <div className="term-name">
            <div className="term-name-label">
              {props.country}
            </div>
          </div>
        </div>
      </div>
      <div className="card-member__filter-sectors">
        {props.sectors.map((item, i) => (
          <div key={i} className="term-container">
            <div className="term">
              <div className="term-name">
                <div className="term-name-label">
                  {item}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </article>
  );
}
