// Generated by `cargo xtask bridgegen` from src/molecules/metric_tile.rs:28. Do not edit.

import type { ReactNode } from 'react';

export interface MetricTileProps {
  /** `AttrValue` — src/molecules/metric_tile.rs:15 */
  label: string;
  /** `AttrValue` — src/molecules/metric_tile.rs:17 */
  value: string;
  /** `Option<AttrValue>` — src/molecules/metric_tile.rs:21; `#[prop_or_default]`, so `None` */
  help?: string | undefined;
  /** `Children` — src/molecules/metric_tile.rs:24; `#[prop_or_default]` */
  children?: ReactNode;
}

export function MetricTile(props: MetricTileProps) {
  return (
    <div className="metric-tile">
      <span className="metric-tile__label">
        {props.label}
      </span>
      <span className="metric-tile__value">
        {props.value}
      </span>
      {props.help != null && (
        <span className="metric-tile__help">
          {props.help}
        </span>
      )}
      <span className="metric-tile__delta">
        {props.children}
      </span>
    </div>
  );
}
