// Generated by `cargo xtask bridgegen` from src/molecules/modal.rs:20. Do not edit.
// Not re-exported from the package index: needs an override — inert hardcoded; needs open: bool upstream (#809)
// Note: [sentinel-integrity] cell base (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:14
// Note: [sentinel-integrity] cell base (primary): the sentinel for `title` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:15

import type { ReactNode } from 'react';

export interface ModalProps {
  /** `AttrValue` — src/molecules/modal.rs:14 */
  id: string;
  /** `AttrValue` — src/molecules/modal.rs:15 */
  title: string;
  /** `Children` — src/molecules/modal.rs:16 */
  children: ReactNode;
}

export function Modal(props: ModalProps) {
  return (
    <div id={props.id} role="dialog" aria-modal="true" aria-label={props.title} inert className="modal">
      <div className="modal-inner">
        <button type="button" data-close-modal={props.id} aria-label="Close" className="submenu-close">
          ✕
        </button>
        <h3>
          {props.title}
        </h3>
        {props.children}
      </div>
    </div>
  );
}
