// Generated by `cargo xtask bridgegen` from src/molecules/modal.rs:28. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:22
// Note: [sentinel-integrity] cell base (primary): the sentinel for `title` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:23
// Note: [sentinel-integrity] cell open_true (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:22
// Note: [sentinel-integrity] cell open_true (primary): the sentinel for `title` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/modal.rs:23

import type { ReactNode } from 'react';

export interface ModalProps {
  /** `bool` — src/molecules/modal.rs:21; `#[prop_or_default]` */
  open?: boolean;
  /** `AttrValue` — src/molecules/modal.rs:22 */
  id: string;
  /** `AttrValue` — src/molecules/modal.rs:23 */
  title: string;
  /** `Children` — src/molecules/modal.rs:24 */
  children: ReactNode;
}

export function Modal($props: ModalProps) {
  const props = {
    ...$props,
    open: $props.open ?? false,
  };
  return (
    <div id={props.id} role="dialog" aria-modal="true" aria-label={props.title} inert={!props.open} className="modal">
      <div className="modal-inner">
        <button type="button" data-close-modal={props.id} aria-label="Close" className="submenu-close">
          ✕
        </button>
        <h3>
          {props.title}
        </h3>
        {props.children}
      </div>
    </div>
  );
}
