// Generated by `cargo xtask bridgegen` from src/molecules/mvo_card.rs:11. Do not edit.

export interface MvoCardProps {
  /** `AttrValue` — src/molecules/mvo_card.rs:6 */
  tag: string;
  /** `AttrValue` — src/molecules/mvo_card.rs:7 */
  description: string;
}

export function MvoCard(props: MvoCardProps) {
  return (
    <div className="mvo-card">
      <span className="mvo-tag">
        <span className="dot" />
        {props.tag}
      </span>
      <p>
        {props.description}
      </p>
    </div>
  );
}
