// Generated by `cargo xtask bridgegen` from src/molecules/nav_dropdown.rs:22. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 4 times, each one whole, so the component renders the prop verbatim in 4 places and `splice` must write the JSX expression into all 4 — src/molecules/nav_dropdown.rs:16
// Note: [sentinel-integrity] cell links_n1 (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 4 times, each one whole, so the component renders the prop verbatim in 4 places and `splice` must write the JSX expression into all 4 — src/molecules/nav_dropdown.rs:16
// Note: [sentinel-integrity] cell links_n2 (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 4 times, each one whole, so the component renders the prop verbatim in 4 places and `splice` must write the JSX expression into all 4 — src/molecules/nav_dropdown.rs:16
// Note: [sentinel-integrity] cell links_n3 (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 4 times, each one whole, so the component renders the prop verbatim in 4 places and `splice` must write the JSX expression into all 4 — src/molecules/nav_dropdown.rs:16

export interface NavDropdownProps {
  /** `AttrValue` — src/molecules/nav_dropdown.rs:16 */
  id: string;
  /** `AttrValue` — src/molecules/nav_dropdown.rs:17 */
  label: string;
  /** `Vec<(&'static str, &'static str)>` — src/molecules/nav_dropdown.rs:18 */
  links: [string, string][];
}

export function NavDropdown(props: NavDropdownProps) {
  return (
    <div style={{ "position": "relative" }} className="menu-item">
      <button type="button" aria-controls={props.id} aria-expanded="false" data-dropdown-trigger={props.id} className="menu-link">
        {props.label}
        <span aria-hidden="true" className="menu-arrow">
          ▾
        </span>
      </button>
      <div id={props.id} inert className="submenu">
        <div className="submenu-content">
          <ul className="submenu-list">
            {props.links.map((item, i) => (
              <li key={i} className="submenu-item">
                <a href={item[0]} className="submenu-link">
                  {item[1]}
                </a>
              </li>
            ))}
          </ul>
        </div>
        <button type="button" data-close={props.id} aria-label="Close" className="submenu-close">
          ✕
        </button>
      </div>
    </div>
  );
}
