// Generated by `cargo xtask bridgegen` from src/molecules/news_card.rs:16. Do not edit.

export interface NewsCardProps {
  /** `AttrValue` — src/molecules/news_card.rs:10 */
  href: string;
  /** `AttrValue` — src/molecules/news_card.rs:11 */
  tag: string;
  /** `AttrValue` — src/molecules/news_card.rs:12 */
  title: string;
}

export function NewsCard(props: NewsCardProps) {
  return (
    <article className="news-card">
      <a href={props.href} className="news-card__link">
        <div className="news-card__image">
          <span className="tag-label tag-label-blue">
            {props.tag}
          </span>
          16:9 image
        </div>
        <div className="news-card__content">
          <h3 className="news-card__title">
            {props.title}
          </h3>
        </div>
      </a>
    </article>
  );
}
