// Generated by `cargo xtask bridgegen` from src/molecules/annotation.rs:38. Do not edit.
// Note: [sentinel-integrity] cell values_n1__values_item_language_none__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n1__values_item_language_some__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n1__values_item_language_none__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n1__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n1__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype_label` (\u{E000}4\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype_label` in this cell — src/ontology.rs:56
// Note: [sentinel-integrity] cell values_n2__values_item_language_none__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n2__values_item_language_some__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n2__values_item_language_none__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n2__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n2__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype_label` (\u{E000}4\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype_label` in this cell — src/ontology.rs:56
// Note: [sentinel-integrity] cell values_n3__values_item_language_none__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n3__values_item_language_some__values_item_datatype_some__values_item_datatype_label_none (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n3__values_item_language_none__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}2\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n3__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype` (\u{E000}3\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype` in this cell — src/ontology.rs:47
// Note: [sentinel-integrity] cell values_n3__values_item_language_some__values_item_datatype_some__values_item_datatype_label_some (primary): the sentinel for `values[0].datatype_label` (\u{E000}4\u{E001}) never reached the markup: in this cell the component does not render the prop at all, or renders something derived from it. Check 2 tells the two apart — if the alphabets agree, nothing derived is there and the emitter must simply not reference `values[0].datatype_label` in this cell — src/ontology.rs:56

import type { LiteralValue } from './types';

export interface OntoAnnotationProps {
  /** `AttrValue` — src/molecules/annotation.rs:16 */
  label: string;
  /** `Vec<LiteralValue>` — src/molecules/annotation.rs:17 */
  values: LiteralValue[];
}

export function OntoAnnotation(props: OntoAnnotationProps) {
  return (
    <div className="annotation">
      <dt className="annotation__label">
        {props.label}
      </dt>
      <dd className="annotation__values">
        {props.values.map((item, i) => (
          <div key={i} className="annotation__row">
            <span className="annotation__text">
              {item.value}
            </span>
            {item.language != null ? (
              <span className="badge badge--default">
                {item.language}
              </span>
            ) : item.datatypeLabel != null && (
              <span className="badge badge--default">
                {item.datatypeLabel}
              </span>
            )}
          </div>
        ))}
      </dd>
    </div>
  );
}
