// Generated by `cargo xtask bridgegen` from src/atoms/onto_badge.rs:66. Do not edit.

export interface OntoBadgeProps {
  /** `AttrValue` — src/atoms/onto_badge.rs:58 */
  label: string;
  /** `BadgeVariant` — src/atoms/onto_badge.rs:60; `#[prop_or_default]` */
  variant?: 'ontology' | 'class' | 'object-property' | 'datatype-property' | 'annotation-property' | 'property' | 'named-individual' | 'other' | 'lang' | 'datatype' | 'deprecated' | 'default';
  /** `Option<AttrValue>` — src/atoms/onto_badge.rs:62; `#[prop_or_default]`, so `None` */
  title?: string | undefined;
}

export function OntoBadge($props: OntoBadgeProps) {
  const props = {
    ...$props,
    variant: $props.variant ?? 'default',
  };
  return (
    <span className={props.variant === "class" ? "badge badge--class" : props.variant === "object-property" ? "badge badge--object-property" : props.variant === "datatype-property" ? "badge badge--datatype-property" : props.variant === "annotation-property" ? "badge badge--annotation-property" : props.variant === "property" ? "badge badge--property" : props.variant === "named-individual" ? "badge badge--named-individual" : ["other", "lang", "datatype", "default"].includes(props.variant) ? "badge badge--default" : props.variant === "deprecated" ? "badge badge--deprecated" : "badge badge--ontology"} title={props.title != null ? props.title : undefined}>
      {props.label}
    </span>
  );
}
