// Generated by `cargo xtask bridgegen` from src/molecules/palette_group.rs:43. Do not edit.
// Note: [sentinel-integrity] cell colors_n1__colors_item_variants_label_none (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n1__colors_item_variants_label_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n2__colors_item_variants_label_none (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n2__colors_item_variants_label_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n3__colors_item_variants_label_none (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n3__colors_item_variants_label_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n1__colors_item_variants_label_none__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n1__colors_item_variants_label_some__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n2__colors_item_variants_label_none__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n2__colors_item_variants_label_some__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n3__colors_item_variants_label_none__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8
// Note: [sentinel-integrity] cell colors_n3__colors_item_variants_label_some__note_some (primary): the sentinel for `colors[0].hex` (\u{E000}3\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/palette_group.rs:8

import type { ColorSpec } from './types';

export interface PaletteGroupProps {
  /** `AttrValue` — src/molecules/palette_group.rs:34 */
  title: string;
  /** `AttrValue` — src/molecules/palette_group.rs:35 */
  description: string;
  /** `Vec<ColorSpec>` — src/molecules/palette_group.rs:36 */
  colors: ColorSpec[];
  /** `Option<AttrValue>` — src/molecules/palette_group.rs:39; `#[prop_or_default]`, so `None` */
  note?: string | undefined;
}

export function PaletteGroup(props: PaletteGroupProps) {
  return (
    <div className="palette-group">
      <h3>
        {props.title}
        {props.note != null && (
          <>
            {" "}
            <span className="ref-note">
              {props.note}
            </span>
          </>
        )}
      </h3>
      <p className="group-desc">
        {props.description}
      </p>
      <div className="swatch-grid">
        {props.colors.map((item, i) => (
          <button key={i} type="button" data-hex={item.hex} className="swatch">
            <span style={{ "background": item.hex, "color": item.ink }} className="swatch-color">
              <span className="swatch-hex">
                {item.hex}
              </span>
              <span className="swatch-copy-flag">
                Copied
              </span>
            </span>
            <span className="swatch-meta">
              <span className="swatch-name">
                {item.name}
              </span>
              <span className="swatch-usage">
                {item.usage}
              </span>
              {item.variantsLabel != null && (
                <span className="swatch-variants">
                  {"Also seen: "}
                  {item.variantsLabel}
                </span>
              )}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}
