// Generated by `cargo xtask bridgegen` from src/molecules/personality_card.rs:11. Do not edit.

export interface PersonalityCardProps {
  /** `AttrValue` — src/molecules/personality_card.rs:6 */
  tag: string;
  /** `AttrValue` — src/molecules/personality_card.rs:7 */
  description: string;
}

export function PersonalityCard(props: PersonalityCardProps) {
  return (
    <div className="personality-card">
      <span className="tag">
        {props.tag}
      </span>
      <p>
        {props.description}
      </p>
    </div>
  );
}
