// Generated by `cargo xtask bridgegen` from src/molecules/pillar_card.rs:13. Do not edit.

export interface PillarCardProps {
  /** `AttrValue` — src/molecules/pillar_card.rs:7 */
  num: string;
  /** `AttrValue` — src/molecules/pillar_card.rs:8 */
  title: string;
  /** `Vec<(&'static str, &'static str)>` — src/molecules/pillar_card.rs:9 */
  points: [string, string][];
}

export function PillarCard(props: PillarCardProps) {
  return (
    <div className="pillar-card">
      <span className="pillar-num">
        {props.num}
      </span>
      <h3>
        {props.title}
      </h3>
      <ul>
        {props.points.map((item, i) => (
          <li key={i}>
            <b>
              {item[0]}
              :
            </b>
            {" "}
            {item[1]}
          </li>
        ))}
      </ul>
    </div>
  );
}
