// Generated by `cargo xtask bridgegen` from src/atoms/pill.rs:28. Do not edit.

import type { ReactNode } from 'react';

export interface PillProps {
  /** `Children` — src/atoms/pill.rs:22 */
  children: ReactNode;
  /** `PillTone` — src/atoms/pill.rs:24; `#[prop_or(PillTone::Ok)]` */
  tone?: 'ok' | 'bad';
}

export function Pill($props: PillProps) {
  const props = {
    ...$props,
    tone: $props.tone ?? 'ok',
  };
  return (
    <span className={props.tone === "bad" ? "name-pill bad" : "name-pill ok"}>
      {props.children}
    </span>
  );
}
