// Generated by `cargo xtask bridgegen` from src/atoms/pill_button.rs:37. Do not edit.

export interface PillButtonProps {
  /** `AttrValue` — src/atoms/pill_button.rs:24 */
  label: string;
  /** `PillButtonKind` — src/atoms/pill_button.rs:26; `#[prop_or(PillButtonKind::Solid)]` */
  kind?: 'solid' | 'glass-light' | 'glass-dark';
  /** `Option<AttrValue>` — src/atoms/pill_button.rs:29; `#[prop_or_default]`, so `None` */
  href?: string | undefined;
  /** `bool` — src/atoms/pill_button.rs:33; `#[prop_or_default]` */
  disabled?: boolean;
}

export function PillButton($props: PillButtonProps) {
  const props = {
    ...$props,
    kind: $props.kind ?? 'solid',
    disabled: $props.disabled ?? false,
  };
  return (
    props.href != null ? (
      <a href={props.href} className={props.kind === "glass-light" ? "pill-btn pill-btn-glass-light" : props.kind === "glass-dark" ? "pill-btn pill-btn-glass-dark" : "pill-btn pill-btn-solid"}>
        {props.label}
      </a>
    ) : (
      <button type="button" className={props.kind === "glass-light" ? "pill-btn pill-btn-glass-light" : props.kind === "glass-dark" ? "pill-btn pill-btn-glass-dark" : "pill-btn pill-btn-solid"} disabled={props.disabled}>
        {props.label}
      </button>
    )
  );
}
