// Generated by `cargo xtask bridgegen` from src/molecules/props_table.rs:40. Do not edit.

import type { PropSpec } from './types';

export interface PropsTableProps {
  /** `AttrValue` — src/molecules/props_table.rs:35 */
  component: string;
  /** `Vec<PropSpec>` — src/molecules/props_table.rs:36 */
  props: PropSpec[];
}

export function PropsTable(props: PropsTableProps) {
  return (
    <div className="props-table-wrap">
      <table className="props-table">
        <caption>
          {props.component}
          {" props"}
        </caption>
        <thead>
          <tr>
            <th scope="col">
              Prop
            </th>
            <th scope="col">
              Type
            </th>
            <th scope="col">
              Default
            </th>
            <th scope="col">
              Notes
            </th>
          </tr>
        </thead>
        <tbody>
          {props.props.map((item, i) => (
            <tr key={i}>
              <td>
                <code>
                  {item.name}
                </code>
              </td>
              <td>
                <code className="props-type">
                  {item.ty}
                </code>
              </td>
              <td>
                {item.default != null ? (
                  <code>
                    {item.default}
                  </code>
                ) : (
                  <span className="props-required">
                    required
                  </span>
                )}
              </td>
              <td>
                {item.doc}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
