// Generated by `cargo xtask bridgegen` from src/molecules/ref_card.rs:14. Do not edit.

export interface RefCardProps {
  /** `AttrValue` — src/molecules/ref_card.rs:7 */
  src: string;
  /** `AttrValue` — src/molecules/ref_card.rs:8 */
  alt: string;
  /** `AttrValue` — src/molecules/ref_card.rs:9 */
  title: string;
  /** `AttrValue` — src/molecules/ref_card.rs:10 */
  description: string;
}

export function RefCard(props: RefCardProps) {
  return (
    <figure className="ref-card">
      <img src={props.src} loading="lazy" alt={props.alt} />
      <figcaption>
        <div className="rc-title">
          {props.title}
        </div>
        <div className="rc-desc">
          {props.description}
        </div>
      </figcaption>
    </figure>
  );
}
