// Generated by `cargo xtask bridgegen` from src/molecules/rule_list_item.rs:28. Do not edit.

import type { ReactNode } from 'react';

export interface RuleListItemProps {
  /** `RuleKind` — src/molecules/rule_list_item.rs:23 */
  kind: 'do' | 'dont' | 'caution';
  /** `Children` — src/molecules/rule_list_item.rs:24 */
  children: ReactNode;
}

export function RuleListItem(props: RuleListItemProps) {
  return (
    <li className={props.kind === "dont" ? "dont" : props.kind === "caution" ? "caution" : "do"}>
      {props.children}
    </li>
  );
}
