// Generated by `cargo xtask bridgegen` from src/molecules/score_donut.rs:29. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `label` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:22
// Note: [sentinel-integrity] cell base (primary): the sentinel for `caption` (\u{E000}2\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:25
// Note: [sentinel-integrity] cell band_warning (primary): the sentinel for `label` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:22
// Note: [sentinel-integrity] cell band_warning (primary): the sentinel for `caption` (\u{E000}2\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:25
// Note: [sentinel-integrity] cell band_danger (primary): the sentinel for `label` (\u{E000}1\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:22
// Note: [sentinel-integrity] cell band_danger (primary): the sentinel for `caption` (\u{E000}2\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/score_donut.rs:25

export interface ScoreDonutProps {
  /** `AttrValue` — src/molecules/score_donut.rs:19 */
  dashArray: string;
  /** `ScoreBand` — src/molecules/score_donut.rs:20 */
  band: 'good' | 'warning' | 'danger';
  /** `AttrValue` — src/molecules/score_donut.rs:22 */
  label: string;
  /** `AttrValue` — src/molecules/score_donut.rs:25 */
  caption: string;
}

export function ScoreDonut(props: ScoreDonutProps) {
  return (
    <figure className="chart-donut">
      <svg viewBox="0 0 120 120" role="img" aria-label={`${props.caption}: ${props.label}`} className="chart-donut__svg">
        <circle cx="60" cy="60" r="45" strokeDasharray="282.7433388230814" className="chart-donut__track" />
        <circle cx="60" cy="60" r="45" strokeDasharray={props.dashArray} transform="rotate(-90 60 60)" className={props.band === "warning" ? "chart-donut__value chart-donut__value--warning" : props.band === "danger" ? "chart-donut__value chart-donut__value--danger" : "chart-donut__value chart-donut__value--good"} />
        <text x="60" y="60" textAnchor="middle" dominantBaseline="central" className="chart-donut__label">
          {props.label}
        </text>
      </svg>
      <figcaption className="chart-donut__caption">
        {props.caption}
      </figcaption>
    </figure>
  );
}
