// Generated by `cargo xtask bridgegen` from src/molecules/section_head.rs:15. Do not edit.

export interface SectionHeadProps {
  /** `AttrValue` — src/molecules/section_head.rs:9 */
  number: string;
  /** `AttrValue` — src/molecules/section_head.rs:10 */
  kicker: string;
  /** `AttrValue` — src/molecules/section_head.rs:11 */
  title: string;
}

export function SectionHead(props: SectionHeadProps) {
  return (
    <div className="section-head">
      <div className="badge-num">
        {props.number}
      </div>
      <div>
        <span className="kicker">
          {props.kicker}
        </span>
        <h2>
          {props.title}
        </h2>
      </div>
    </div>
  );
}
