// Generated by `cargo xtask bridgegen` from src/molecules/shape_card.rs:12. Do not edit.

import type { ReactNode } from 'react';

export interface ShapeCardProps {
  /** `Html` — src/molecules/shape_card.rs:6 */
  demo: ReactNode;
  /** `AttrValue` — src/molecules/shape_card.rs:7 */
  title: string;
  /** `AttrValue` — src/molecules/shape_card.rs:8 */
  description: string;
}

export function ShapeCard(props: ShapeCardProps) {
  return (
    <div className="shape-card">
      <div className="shape-demo">
        {props.demo}
      </div>
      <h4>
        {props.title}
      </h4>
      <p>
        {props.description}
      </p>
    </div>
  );
}
