// Generated by `cargo xtask bridgegen` from src/organisms/simple_footer.rs:13. Do not edit.

import type { NavLink } from './types';

export interface SimpleFooterProps {
  /** `AttrValue` — src/organisms/simple_footer.rs:8 */
  text: string;
  /** `NavLink` — src/organisms/simple_footer.rs:9 */
  link: NavLink;
}

export function SimpleFooter(props: SimpleFooterProps) {
  return (
    <footer className="icons-footer">
      <div className="wrap bottom-line">
        <span>
          {props.text}
        </span>
        <span>
          <a href={props.link.href}>
            {"← "}
            {props.link.label}
          </a>
        </span>
      </div>
    </footer>
  );
}
