// Generated by `cargo xtask bridgegen` from src/organisms/site_header.rs:96. Do not edit.

import type { SiteNavLink } from './types';

export interface SiteHeaderProps {
  /** `Vec<SiteNavLink>` — src/organisms/site_header.rs:90 */
  links: SiteNavLink[];
  /** `bool` — src/organisms/site_header.rs:92; `#[prop_or_default]` */
  showLogin?: boolean;
}

export function SiteHeader($props: SiteHeaderProps) {
  const props = {
    ...$props,
    showLogin: $props.showLogin ?? false,
  };
  return (
    <header className="site-header">
      <div className="wrap site-header__wrap">
        <a href="index.html" aria-label="EONA-X" className="site-header__logo site-header__logo--top">
          <img src="logo/logo-transparent.svg" alt="" width="38" height="36" />
        </a>
        <nav aria-label="Developer portal" className="site-header__pill">
          <a href="index.html" aria-label="EONA-X" className="site-header__logo site-header__logo--pill">
            <img src="logo/logo-transparent.svg" alt="" width="28" height="27" />
          </a>
          {props.links.map((item, i) => (
            <a key={i} href={item.href} className="site-header__link" aria-current={item.current ? "page" : undefined}>
              {item.label}
            </a>
          ))}
          <div className="site-header__actions site-header__actions--pill">
            <span className="site-header__lang">
              EN
            </span>
            {props.showLogin && (
              <button type="button" disabled className="pill-btn pill-btn-glass-light">
                Log in
              </button>
            )}
          </div>
        </nav>
        <div className="site-header__actions site-header__actions--top">
          <span className="site-header__lang">
            EN
          </span>
          {props.showLogin && (
            <button type="button" disabled className="pill-btn pill-btn-glass-light">
              Log in
            </button>
          )}
        </div>
      </div>
    </header>
  );
}
