// Generated by `cargo xtask bridgegen` from src/molecules/swatch.rs:44. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `hex` (\u{E000}0\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/swatch.rs:23
// Note: [sentinel-integrity] cell variants_some (primary): the sentinel for `hex` (\u{E000}0\u{E001}) appears 3 times, each one whole, so the component renders the prop verbatim in 3 places and `splice` must write the JSX expression into all 3 — src/molecules/swatch.rs:23

export interface SwatchProps {
  /** `AttrValue` — src/molecules/swatch.rs:23 */
  hex: string;
  /** `AttrValue` — src/molecules/swatch.rs:31 */
  ink: string;
  /** `AttrValue` — src/molecules/swatch.rs:32 */
  name: string;
  /** `AttrValue` — src/molecules/swatch.rs:33 */
  usage: string;
  /** `Option<AttrValue>` — src/molecules/swatch.rs:40; `#[prop_or_default]`, so `None` */
  variants?: string | undefined;
}

export function Swatch(props: SwatchProps) {
  return (
    <button type="button" data-hex={props.hex} className="swatch">
      <span style={{ "background": props.hex, "color": props.ink }} className="swatch-color">
        <span className="swatch-hex">
          {props.hex}
        </span>
        <span className="swatch-copy-flag">
          Copied
        </span>
      </span>
      <span className="swatch-meta">
        <span className="swatch-name">
          {props.name}
        </span>
        <span className="swatch-usage">
          {props.usage}
        </span>
        {props.variants != null && (
          <span className="swatch-variants">
            {"Also seen: "}
            {props.variants}
          </span>
        )}
      </span>
    </button>
  );
}
