// Generated by `cargo xtask bridgegen` from src/atoms/tag_label.rs:27. Do not edit.

export interface TagLabelProps {
  /** `AttrValue` — src/atoms/tag_label.rs:21 */
  text: string;
  /** `TagLabelTone` — src/atoms/tag_label.rs:23; `#[prop_or(TagLabelTone::Default)]` */
  tone?: 'default' | 'blue';
}

export function TagLabel($props: TagLabelProps) {
  const props = {
    ...$props,
    tone: $props.tone ?? 'default',
  };
  return (
    <span className={props.tone === "blue" ? "tag-label tag-label-blue" : "tag-label"}>
      {props.text}
    </span>
  );
}
