// Generated by `cargo xtask bridgegen` from src/molecules/text_field.rs:22. Do not edit.
// Note: [sentinel-integrity] cell base (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/text_field.rs:13
// Note: [sentinel-integrity] cell kind_textarea (primary): the sentinel for `id` (\u{E000}0\u{E001}) appears 2 times, each one whole, so the component renders the prop verbatim in 2 places and `splice` must write the JSX expression into all 2 — src/molecules/text_field.rs:13

export interface TextFieldProps {
  /** `AttrValue` — src/molecules/text_field.rs:13 */
  id: string;
  /** `AttrValue` — src/molecules/text_field.rs:14 */
  label: string;
  /** `TextFieldKind` — src/molecules/text_field.rs:16; `#[prop_or(TextFieldKind::Input)]` */
  kind?: 'input' | 'textarea';
  /** `AttrValue` — src/molecules/text_field.rs:18; `#[prop_or_default]` */
  placeholder?: string;
}

export function TextField($props: TextFieldProps) {
  const props = {
    ...$props,
    kind: $props.kind ?? 'input',
    placeholder: $props.placeholder ?? '',
  };
  return (
    <div className="text-field">
      <label htmlFor={props.id}>
        {props.label}
      </label>
      {props.kind === "textarea" ? (
        <textarea id={props.id} placeholder={props.placeholder} />
      ) : (
        <input id={props.id} type="text" placeholder={props.placeholder} />
      )}
    </div>
  );
}
