// Generated by `cargo xtask bridgegen` from src/molecules/type_scale_row.rs:14. Do not edit.

import type { ReactNode } from 'react';

export interface TypeScaleRowProps {
  /** `AttrValue` — src/molecules/type_scale_row.rs:8 */
  role: string;
  /** `Html` — src/molecules/type_scale_row.rs:9 */
  sample: ReactNode;
  /** `AttrValue` — src/molecules/type_scale_row.rs:10 */
  spec: string;
}

export function TypeScaleRow(props: TypeScaleRowProps) {
  return (
    <div className="type-scale-row">
      <div className="role">
        {props.role}
      </div>
      {props.sample}
      <div className="spec">
        {props.spec}
      </div>
    </div>
  );
}
