// Generated by `cargo xtask bridgegen` from the eona-ui-toolkit Yew crate. Do not edit.
//
// The plain structs a generated component's props reach. Field names are camel-cased from
// Rust; each carries the `file:line` it came from, and is optional when
// the Rust field is `Option<T>`.

/** `ColorSpec` — src/molecules/palette_group.rs:6 */
export interface ColorSpec {
  /** `AttrValue` — src/molecules/palette_group.rs:7 */
  name: string;
  /** `AttrValue` — src/molecules/palette_group.rs:8 */
  hex: string;
  /** `AttrValue` — src/molecules/palette_group.rs:9 */
  usage: string;
  /** `AttrValue` — src/molecules/palette_group.rs:12 */
  ink: string;
  /** `Option<AttrValue>` — src/molecules/palette_group.rs:14 */
  variantsLabel?: string | undefined;
}

/** `LiteralValue` — src/ontology.rs:44 */
export interface LiteralValue {
  /** `String` — src/ontology.rs:45 */
  value: string;
  /** `Option<String>` — src/ontology.rs:46 */
  language?: string | undefined;
  /** `Option<String>` — src/ontology.rs:47 */
  datatype?: string | undefined;
  /** `Option<String>` — src/ontology.rs:56 */
  datatypeLabel?: string | undefined;
}

/** `NavLink` — src/organisms/main_nav.rs:4 */
export interface NavLink {
  /** `AttrValue` — src/organisms/main_nav.rs:5 */
  href: string;
  /** `AttrValue` — src/organisms/main_nav.rs:6 */
  label: string;
}

/** `PropSpec` — src/molecules/props_table.rs:6 */
export interface PropSpec {
  /** `AttrValue` — src/molecules/props_table.rs:7 */
  name: string;
  /** `AttrValue` — src/molecules/props_table.rs:8 */
  ty: string;
  /** `Option<AttrValue>` — src/molecules/props_table.rs:11 */
  default?: string | undefined;
  /** `AttrValue` — src/molecules/props_table.rs:12 */
  doc: string;
}

/** `SiteNavLink` — src/organisms/site_header.rs:6 */
export interface SiteNavLink {
  /** `AttrValue` — src/organisms/site_header.rs:7 */
  href: string;
  /** `AttrValue` — src/organisms/site_header.rs:8 */
  label: string;
  /** `bool` — src/organisms/site_header.rs:9 */
  current: boolean;
}
