// Generated by `cargo xtask bridgegen` from src/molecules/usage_example.rs:24. Do not edit.

import type { ReactNode } from 'react';

export interface UsageExampleProps {
  /** `AttrValue` — src/molecules/usage_example.rs:14 */
  source: string;
  /** `bool` — src/molecules/usage_example.rs:18; `#[prop_or_default]` */
  onDark?: boolean;
  /** `Html` — src/molecules/usage_example.rs:20 */
  children: ReactNode;
}

export function UsageExample($props: UsageExampleProps) {
  const props = {
    ...$props,
    onDark: $props.onDark ?? false,
  };
  return (
    <div className="usage-example">
      <div className={props.onDark ? "usage-preview usage-preview-dark" : "usage-preview"}>
        {props.children}
      </div>
      <div className="code-block">
        <div className="code-block-bar">
          <span className="code-block-lang">
            rust
          </span>
          <button type="button" aria-label="Copy this snippet" className="code-block-copy">
            Copy
          </button>
        </div>
        <pre className="code-block-pre">
          <code className="language-rust">
            {props.source}
          </code>
        </pre>
      </div>
    </div>
  );
}
