//! Generated by `cargo xtask bridgegen` from the eona-ui-toolkit Yew crate. Do not edit.
//!
//! One usage snippet per component, in both stacks. The React half is
//! derived from the same `abi/toolkit.abi.json` entry as the Yew half, so a
//! prop added in `src/` reaches both panes of the components page at once.
//!
//! Outside `src/` on purpose: `src_hash` is taken over `src/**/*.rs`
//! (xtask/src/parse.rs), and a generated file inside `src/` would be an input
//! to the hash of the document that describes it.
//!
//! src_hash e2f87d37a98628ba1179b6685c343ac908f0107ef8e37da01f0b07580c98f5f9

/// Whether a component ships in `@eona-x/ui-toolkit-react`.
///
/// Five do not — one needs an override and four are quarantined — and a page
/// that showed them JSX anyway would hand a reader an import that does not
/// resolve. `abi/overrides.toml` is where the disposition comes from.
pub enum ReactSnippet {
    Available { import: &'static str, jsx: &'static str },
    Unavailable { why: &'static str, disposition: &'static str, tracked_by: &'static str },
}

/// One component's usage snippet, in both stacks.
pub struct Snippet {
    pub component: &'static str,
    /// `file:line` of the `#[function_component]`.
    pub source: &'static str,
    /// The `use` lines the Yew snippet needs, newline-separated.
    pub yew_uses: &'static str,
    pub yew: &'static str,
    pub react: ReactSnippet,
}

/// Every component the crate defines, sorted by name — excluded ones
/// included, so a component cannot leave this table by being absent from a
/// list nobody counts.
pub static SNIPPETS: &[Snippet] = &[
    Snippet {
        component: r#"AccordionItem"#,
        source: r#"src/molecules/accordion_item.rs:17"#,
        yew_uses: r#"use eona_ui_toolkit::AccordionItem;"#,
        yew: r#"<AccordionItem open={true} title="Title">
    { "Children go here." }
</AccordionItem>"#,
        react: ReactSnippet::Available {
            import: r#"import { AccordionItem } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<AccordionItem open title="Title">
  Children go here.
</AccordionItem>"#,
        },
    },
    Snippet {
        component: r#"BadgeNum"#,
        source: r#"src/atoms/badge_num.rs:11"#,
        yew_uses: r#"use eona_ui_toolkit::BadgeNum;"#,
        yew: r#"<BadgeNum number="01" />"#,
        react: ReactSnippet::Available {
            import: r#"import { BadgeNum } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<BadgeNum number="01" />"#,
        },
    },
    Snippet {
        component: r#"BgCheckItem"#,
        source: r#"src/molecules/bg_check_item.rs:16"#,
        yew_uses: r#"use eona_ui_toolkit::BgCheckItem;"#,
        yew: r##"<BgCheckItem
    background="#fff"
    border="1px solid rgba(4,5,83,.12)"
    color="var(--eona-navy)"
    icon="✓"
    label="Label"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { BgCheckItem } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<BgCheckItem
  background="#fff"
  border="1px solid rgba(4,5,83,.12)"
  color="var(--eona-navy)"
  icon="✓"
  label="Label"
/>"##,
        },
    },
    Snippet {
        component: r#"Button"#,
        source: r#"src/atoms/button.rs:30"#,
        yew_uses: r#"use eona_ui_toolkit::{Button, ButtonVariant};"#,
        yew: r##"<Button href="#" label="Label" variant={ButtonVariant::Ghost} />"##,
        react: ReactSnippet::Available {
            import: r#"import { Button } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<Button href="#" label="Label" variant="ghost" />"##,
        },
    },
    Snippet {
        component: r#"Callout"#,
        source: r#"src/molecules/callout.rs:13"#,
        yew_uses: r#"use eona_ui_toolkit::Callout;"#,
        yew: r#"<Callout english="English" french="French" label="Label" />"#,
        react: ReactSnippet::Available {
            import: r#"import { Callout } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<Callout english="English" french="French" label="Label" />"#,
        },
    },
    Snippet {
        component: r#"CaseCard"#,
        source: r#"src/molecules/case_card.rs:15"#,
        yew_uses: r#"use eona_ui_toolkit::CaseCard;"#,
        yew: r##"<CaseCard href="#" tag="Tag" title="Title" />"##,
        react: ReactSnippet::Available {
            import: r#"import { CaseCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<CaseCard href="#" tag="Tag" title="Title" />"##,
        },
    },
    Snippet {
        component: r#"CodeBlock"#,
        source: r#"src/atoms/code_block.rs:27"#,
        yew_uses: r#"use eona_ui_toolkit::CodeBlock;"#,
        yew: r##"<CodeBlock code={r#"let label = "Go";"#} copyable={false} language="rust" />"##,
        react: ReactSnippet::Available {
            import: r#"import { CodeBlock } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<CodeBlock code={"let label = \"Go\";"} copyable={false} language="rust" />"#,
        },
    },
    Snippet {
        component: r#"ComponentsGallery"#,
        source: r#"src/organisms/components_gallery.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::ComponentsGallery;"#,
        yew: r#"<ComponentsGallery />"#,
        react: ReactSnippet::Unavailable {
            why: r#"never generated — out of scope by rule: zero-prop demo section"#,
            disposition: "",
            tracked_by: "",
        },
    },
    Snippet {
        component: r#"DatasetCard"#,
        source: r#"src/molecules/dataset_card.rs:57"#,
        yew_uses: r#"use eona_ui_toolkit::DatasetCard;"#,
        yew: r##"<DatasetCard
    action_label="View documentation"
    badge="Badge"
    badge_class="Badge Class"
    description="Description"
    href="#"
    initial="Initial"
    publisher="Publisher"
    thumbnail="/assets/placeholder.svg"
    title="Title"
    version="Version"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { DatasetCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<DatasetCard
  actionLabel="View documentation"
  badge="Badge"
  badgeClass="Badge Class"
  description="Description"
  href="#"
  initial="Initial"
  publisher="Publisher"
  thumbnail="/assets/placeholder.svg"
  title="Title"
  version="Version"
/>"##,
        },
    },
    Snippet {
        component: r#"DeclCard"#,
        source: r#"src/molecules/decl_card.rs:17"#,
        yew_uses: r#"use eona_ui_toolkit::DeclCard;"#,
        yew: r#"<DeclCard
    alt="EONA-X logo"
    category="Category"
    decl_type="Decl Type"
    description="Description"
    src="/assets/placeholder.svg"
    title="Title"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { DeclCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<DeclCard
  alt="EONA-X logo"
  category="Category"
  declType="Decl Type"
  description="Description"
  src="/assets/placeholder.svg"
  title="Title"
/>"#,
        },
    },
    Snippet {
        component: r#"DemoPage"#,
        source: r#"src/demo.rs:62"#,
        yew_uses: r#"use eona_ui_toolkit::{NavLink, SiteNavLink};
use eona_ui_toolkit::demo::DemoPage;"#,
        yew: r##"<DemoPage
    footer_link={NavLink { href: "#".into(), label: "Label".into() }}
    footer_text="Footer Text"
    nav={vec![SiteNavLink { href: "#".into(), label: "Label".into(), current: false }]}
/>"##,
        react: ReactSnippet::Unavailable {
            why: r#"never generated — out of scope by rule: crate showcase page"#,
            disposition: "",
            tracked_by: "",
        },
    },
    Snippet {
        component: r#"EvolutionBadge"#,
        source: r#"src/atoms/evolution_badge.rs:23"#,
        yew_uses: r#"use eona_ui_toolkit::EvolutionBadge;
use eona_ui_toolkit::chart::Trend;"#,
        yew: r#"<EvolutionBadge trend={Trend::Up} value="An annotation value" />"#,
        react: ReactSnippet::Available {
            import: r#"import { EvolutionBadge } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<EvolutionBadge trend="up" value="An annotation value" />"#,
        },
    },
    Snippet {
        component: r#"Hero"#,
        source: r#"src/organisms/hero.rs:35"#,
        yew_uses: r#"use eona_ui_toolkit::{Hero, HeroVariant};"#,
        yew: r#"<Hero
    eyebrow="Eyebrow"
    lede="Lede"
    title_suffix="Title Suffix"
    variant={HeroVariant::Full}
>
    { "Children go here." }
</Hero>"#,
        react: ReactSnippet::Available {
            import: r#"import { Hero } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<Hero
  eyebrow="Eyebrow"
  lede="Lede"
  titleSuffix="Title Suffix"
  variant="full"
>
  Children go here.
</Hero>"#,
        },
    },
    Snippet {
        component: r#"HeroFilter"#,
        source: r#"src/organisms/hero_filter.rs:34"#,
        yew_uses: r#"use eona_ui_toolkit::HeroFilter;"#,
        yew: r#"<HeroFilter description="Description" title="Title" with_backdrop={true}>
    { "Children go here." }
</HeroFilter>"#,
        react: ReactSnippet::Available {
            import: r#"import { HeroFilter } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<HeroFilter description="Description" title="Title" withBackdrop>
  Children go here.
</HeroFilter>"#,
        },
    },
    Snippet {
        component: r#"IntegrationSection"#,
        source: r#"src/organisms/integration_section.rs:33"#,
        yew_uses: r#"use eona_ui_toolkit::IntegrationSection;"#,
        yew: r#"<IntegrationSection />"#,
        react: ReactSnippet::Unavailable {
            why: r#"never generated — out of scope by rule: zero-prop demo section"#,
            disposition: "",
            tracked_by: "",
        },
    },
    Snippet {
        component: r#"LogoDownloadCard"#,
        source: r#"src/molecules/logo_download_card.rs:22"#,
        yew_uses: r#"use eona_ui_toolkit::LogoDownloadCard;"#,
        yew: r#"<LogoDownloadCard
    download_name="Download Name"
    file="/assets/eona-x-logo.svg"
    is_transparent={true}
    label="Label"
    preview_style="background:var(--eona-navy);padding:24px;"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { LogoDownloadCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<LogoDownloadCard
  downloadName="Download Name"
  file="/assets/eona-x-logo.svg"
  isTransparent
  label="Label"
  previewStyle="background:var(--eona-navy);padding:24px;"
/>"#,
        },
    },
    Snippet {
        component: r#"MainNav"#,
        source: r#"src/organisms/main_nav.rs:26"#,
        yew_uses: r#"use eona_ui_toolkit::{MainNav, NavLink};"#,
        yew: r##"<MainNav
    back={NavLink { href: "#".into(), label: "Label".into() }}
    links={vec![NavLink { href: "#".into(), label: "Label".into() }]}
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { MainNav } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<MainNav
  back={{ href: "#", label: "Label" }}
  links={[{ href: "#", label: "Label" }]}
/>"##,
        },
    },
    Snippet {
        component: r#"MemberCard"#,
        source: r#"src/molecules/member_card.rs:11"#,
        yew_uses: r#"use eona_ui_toolkit::MemberCard;"#,
        yew: r#"<MemberCard name="Name" />"#,
        react: ReactSnippet::Available {
            import: r#"import { MemberCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<MemberCard name="Name" />"#,
        },
    },
    Snippet {
        component: r#"MemberFilterCard"#,
        source: r#"src/molecules/member_filter_card.rs:18"#,
        yew_uses: r#"use eona_ui_toolkit::MemberFilterCard;"#,
        yew: r#"<MemberFilterCard
    country="Country"
    member_type="Member Type"
    name="Name"
    sectors={vec!["Mobility"]}
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { MemberFilterCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<MemberFilterCard
  country="Country"
  memberType="Member Type"
  name="Name"
  sectors={["Mobility"]}
/>"#,
        },
    },
    Snippet {
        component: r#"MetricTile"#,
        source: r#"src/molecules/metric_tile.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::MetricTile;"#,
        yew: r#"<MetricTile help="Help" label="Label" value="An annotation value">
    { "Children go here." }
</MetricTile>"#,
        react: ReactSnippet::Available {
            import: r#"import { MetricTile } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<MetricTile help="Help" label="Label" value="An annotation value">
  Children go here.
</MetricTile>"#,
        },
    },
    Snippet {
        component: r#"Modal"#,
        source: r#"src/molecules/modal.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::Modal;"#,
        yew: r#"<Modal id="example" open={true} title="Title">
    { "Children go here." }
</Modal>"#,
        react: ReactSnippet::Available {
            import: r#"import { Modal } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<Modal id="example" open title="Title">
  Children go here.
</Modal>"#,
        },
    },
    Snippet {
        component: r#"MvoCard"#,
        source: r#"src/molecules/mvo_card.rs:11"#,
        yew_uses: r#"use eona_ui_toolkit::MvoCard;"#,
        yew: r#"<MvoCard description="Description" tag="Tag" />"#,
        react: ReactSnippet::Available {
            import: r#"import { MvoCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<MvoCard description="Description" tag="Tag" />"#,
        },
    },
    Snippet {
        component: r#"NavDropdown"#,
        source: r#"src/molecules/nav_dropdown.rs:22"#,
        yew_uses: r#"use eona_ui_toolkit::NavDropdown;"#,
        yew: r##"<NavDropdown id="example" label="Label" links={vec![("#", "About")]} />"##,
        react: ReactSnippet::Available {
            import: r#"import { NavDropdown } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<NavDropdown id="example" label="Label" links={[["#", "About"]]} />"##,
        },
    },
    Snippet {
        component: r#"NewsCard"#,
        source: r#"src/molecules/news_card.rs:16"#,
        yew_uses: r#"use eona_ui_toolkit::NewsCard;"#,
        yew: r##"<NewsCard href="#" tag="Tag" title="Title" />"##,
        react: ReactSnippet::Available {
            import: r#"import { NewsCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<NewsCard href="#" tag="Tag" title="Title" />"##,
        },
    },
    Snippet {
        component: r#"OntoAnnotation"#,
        source: r#"src/molecules/annotation.rs:38"#,
        yew_uses: r#"use eona_ui_toolkit::OntoAnnotation;
use eona_ui_toolkit::ontology::LiteralValue;"#,
        yew: r#"<OntoAnnotation
    label="Label"
    values={vec![LiteralValue { value: "An annotation value".into(), language: None, datatype: None, datatype_label: None }]}
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { OntoAnnotation } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<OntoAnnotation label="Label" values={[{ value: "An annotation value" }]} />"#,
        },
    },
    Snippet {
        component: r#"OntoBadge"#,
        source: r#"src/atoms/onto_badge.rs:66"#,
        yew_uses: r#"use eona_ui_toolkit::{BadgeVariant, OntoBadge};"#,
        yew: r#"<OntoBadge label="Label" title="Title" variant={BadgeVariant::Lang} />"#,
        react: ReactSnippet::Available {
            import: r#"import { OntoBadge } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<OntoBadge label="Label" title="Title" variant="lang" />"#,
        },
    },
    Snippet {
        component: r#"OntologySection"#,
        source: r#"src/organisms/ontology_section.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::OntologySection;"#,
        yew: r#"<OntologySection />"#,
        react: ReactSnippet::Unavailable {
            why: r#"never generated — out of scope by rule: zero-prop demo section"#,
            disposition: "",
            tracked_by: "",
        },
    },
    Snippet {
        component: r#"PaletteGroup"#,
        source: r#"src/molecules/palette_group.rs:43"#,
        yew_uses: r#"use eona_ui_toolkit::{ColorSpec, PaletteGroup};"#,
        yew: r##"<PaletteGroup
    colors={vec![ColorSpec { name: "Name".into(), hex: "#040553".into(), usage: "Primary brand colour".into(), ink: "Ink".into(), variants_label: None }]}
    description="Description"
    note="Note"
    title="Title"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { PaletteGroup } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<PaletteGroup
  colors={[{ name: "Name", hex: "#040553", usage: "Primary brand colour", ink: "Ink" }]}
  description="Description"
  note="Note"
  title="Title"
/>"##,
        },
    },
    Snippet {
        component: r#"PersonalityCard"#,
        source: r#"src/molecules/personality_card.rs:11"#,
        yew_uses: r#"use eona_ui_toolkit::PersonalityCard;"#,
        yew: r#"<PersonalityCard description="Description" tag="Tag" />"#,
        react: ReactSnippet::Available {
            import: r#"import { PersonalityCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<PersonalityCard description="Description" tag="Tag" />"#,
        },
    },
    Snippet {
        component: r#"Pill"#,
        source: r#"src/atoms/pill.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::{Pill, PillTone};"#,
        yew: r#"<Pill tone={PillTone::Bad}>
    { "Children go here." }
</Pill>"#,
        react: ReactSnippet::Available {
            import: r#"import { Pill } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<Pill tone="bad">
  Children go here.
</Pill>"#,
        },
    },
    Snippet {
        component: r#"PillButton"#,
        source: r#"src/atoms/pill_button.rs:37"#,
        yew_uses: r#"use eona_ui_toolkit::{PillButton, PillButtonKind};"#,
        yew: r##"<PillButton
    disabled={true}
    href="#"
    kind={PillButtonKind::GlassLight}
    label="Label"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { PillButton } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<PillButton disabled href="#" kind="glass-light" label="Label" />"##,
        },
    },
    Snippet {
        component: r#"PillarCard"#,
        source: r#"src/molecules/pillar_card.rs:13"#,
        yew_uses: r#"use eona_ui_toolkit::PillarCard;"#,
        yew: r#"<PillarCard
    num="01"
    points={vec![("Open", "by default, not by exception")]}
    title="Title"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { PillarCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<PillarCard
  num="01"
  points={[["Open", "by default, not by exception"]]}
  title="Title"
/>"#,
        },
    },
    Snippet {
        component: r#"PropsTable"#,
        source: r#"src/molecules/props_table.rs:40"#,
        yew_uses: r#"use eona_ui_toolkit::{PropSpec, PropsTable};"#,
        yew: r#"<PropsTable
    component="Button"
    props={vec![PropSpec { name: "Name".into(), ty: "AttrValue".into(), default: None, doc: "What the prop does.".into() }]}
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { PropsTable } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<PropsTable
  component="Button"
  props={[{ name: "Name", ty: "AttrValue", doc: "What the prop does." }]}
/>"#,
        },
    },
    Snippet {
        component: r#"RefCard"#,
        source: r#"src/molecules/ref_card.rs:14"#,
        yew_uses: r#"use eona_ui_toolkit::RefCard;"#,
        yew: r#"<RefCard
    alt="EONA-X logo"
    description="Description"
    src="/assets/placeholder.svg"
    title="Title"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { RefCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<RefCard
  alt="EONA-X logo"
  description="Description"
  src="/assets/placeholder.svg"
  title="Title"
/>"#,
        },
    },
    Snippet {
        component: r#"RuleListItem"#,
        source: r#"src/molecules/rule_list_item.rs:28"#,
        yew_uses: r#"use eona_ui_toolkit::{RuleKind, RuleListItem};"#,
        yew: r#"<RuleListItem kind={RuleKind::Do}>
    { "Children go here." }
</RuleListItem>"#,
        react: ReactSnippet::Available {
            import: r#"import { RuleListItem } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<RuleListItem kind="do">
  Children go here.
</RuleListItem>"#,
        },
    },
    Snippet {
        component: r#"ScoreDonut"#,
        source: r#"src/molecules/score_donut.rs:29"#,
        yew_uses: r#"use eona_ui_toolkit::ScoreDonut;
use eona_ui_toolkit::chart::ScoreBand;"#,
        yew: r#"<ScoreDonut
    band={ScoreBand::Good}
    caption="Caption"
    dash_array="Dash Array"
    label="Label"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { ScoreDonut } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<ScoreDonut
  band="good"
  caption="Caption"
  dashArray="Dash Array"
  label="Label"
/>"#,
        },
    },
    Snippet {
        component: r#"SectionHead"#,
        source: r#"src/molecules/section_head.rs:15"#,
        yew_uses: r#"use eona_ui_toolkit::SectionHead;"#,
        yew: r#"<SectionHead kicker="Kicker" number="01" title="Title" />"#,
        react: ReactSnippet::Available {
            import: r#"import { SectionHead } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<SectionHead kicker="Kicker" number="01" title="Title" />"#,
        },
    },
    Snippet {
        component: r#"ShapeCard"#,
        source: r#"src/molecules/shape_card.rs:12"#,
        yew_uses: r#"use eona_ui_toolkit::ShapeCard;
use yew::prelude::*;"#,
        yew: r#"<ShapeCard
    demo={html! { <span>{ "Slot content." }</span> }}
    description="Description"
    title="Title"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { ShapeCard } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<ShapeCard
  demo={<span>Slot content.</span>}
  description="Description"
  title="Title"
/>"#,
        },
    },
    Snippet {
        component: r#"SimpleFooter"#,
        source: r#"src/organisms/simple_footer.rs:13"#,
        yew_uses: r#"use eona_ui_toolkit::{NavLink, SimpleFooter};"#,
        yew: r##"<SimpleFooter
    link={NavLink { href: "#".into(), label: "Label".into() }}
    text="Text"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { SimpleFooter } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<SimpleFooter link={{ href: "#", label: "Label" }} text="Text" />"##,
        },
    },
    Snippet {
        component: r#"SiteHeader"#,
        source: r#"src/organisms/site_header.rs:96"#,
        yew_uses: r#"use eona_ui_toolkit::{SiteHeader, SiteNavLink};"#,
        yew: r##"<SiteHeader
    links={vec![SiteNavLink { href: "#".into(), label: "Label".into(), current: false }]}
    show_login={true}
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { SiteHeader } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<SiteHeader
  links={[{ href: "#", label: "Label", current: false }]}
  showLogin
/>"##,
        },
    },
    Snippet {
        component: r#"Swatch"#,
        source: r#"src/molecules/swatch.rs:44"#,
        yew_uses: r#"use eona_ui_toolkit::Swatch;"#,
        yew: r##"<Swatch
    hex="#040553"
    ink="Ink"
    name="Name"
    usage="Primary brand colour"
    variants="Variants"
/>"##,
        react: ReactSnippet::Available {
            import: r#"import { Swatch } from '@eona-x/ui-toolkit-react';"#,
            jsx: r##"<Swatch
  hex="#040553"
  ink="Ink"
  name="Name"
  usage="Primary brand colour"
  variants="Variants"
/>"##,
        },
    },
    Snippet {
        component: r#"TagLabel"#,
        source: r#"src/atoms/tag_label.rs:27"#,
        yew_uses: r#"use eona_ui_toolkit::{TagLabel, TagLabelTone};"#,
        yew: r#"<TagLabel text="Text" tone={TagLabelTone::Blue} />"#,
        react: ReactSnippet::Available {
            import: r#"import { TagLabel } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<TagLabel text="Text" tone="blue" />"#,
        },
    },
    Snippet {
        component: r#"TextField"#,
        source: r#"src/molecules/text_field.rs:22"#,
        yew_uses: r#"use eona_ui_toolkit::{TextField, TextFieldKind};"#,
        yew: r#"<TextField
    id="example"
    kind={TextFieldKind::Textarea}
    label="Label"
    placeholder="Placeholder"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { TextField } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<TextField
  id="example"
  kind="textarea"
  label="Label"
  placeholder="Placeholder"
/>"#,
        },
    },
    Snippet {
        component: r#"TypeScaleRow"#,
        source: r#"src/molecules/type_scale_row.rs:14"#,
        yew_uses: r#"use eona_ui_toolkit::TypeScaleRow;
use yew::prelude::*;"#,
        yew: r#"<TypeScaleRow
    role="Role"
    sample={html! { <span>{ "Slot content." }</span> }}
    spec="Spec"
/>"#,
        react: ReactSnippet::Available {
            import: r#"import { TypeScaleRow } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<TypeScaleRow role="Role" sample={<span>Slot content.</span>} spec="Spec" />"#,
        },
    },
    Snippet {
        component: r#"UsageExample"#,
        source: r#"src/molecules/usage_example.rs:24"#,
        yew_uses: r#"use eona_ui_toolkit::UsageExample;"#,
        yew: r##"<UsageExample on_dark={true} source={r#"<Button label="Go" />"#}>
    { "Children go here." }
</UsageExample>"##,
        react: ReactSnippet::Available {
            import: r#"import { UsageExample } from '@eona-x/ui-toolkit-react';"#,
            jsx: r#"<UsageExample onDark source={"<Button label=\"Go\" />"}>
  Children go here.
</UsageExample>"#,
        },
    },
];

/// The snippet for a component, by name.
///
/// Keyed on the component name rather than on the snippet text: a lookup keyed
/// on a value is invisible to the generator's verify gate, which renders every
/// component with sentinel props — both alphabets would miss the table, both
/// renders would agree, and the gate would certify a component frozen into the
/// not-found arm. See xtask/README.md, "Handling a quarantine".
pub fn snippet(component: &str) -> Option<&'static Snippet> {
    SNIPPETS
        .binary_search_by(|s| s.component.cmp(component))
        .ok()
        .map(|i| &SNIPPETS[i])
}
