//! Shared Yew component library for the EONA-X design system.
//!
//! Structured as atoms -> molecules -> organisms (increasing composition), matching
//! the "atoms/molecules/elements" vocabulary already used by the static design-system
//! repo's own component gallery. Markup and CSS classes are ported verbatim from
//! `design-system` repo's `charte-graphique-design-system` branch (`brand/index.html`
//! and `brand/tokens.css`) so that consumers linking `assets/tokens.css` +
//! `assets/components.css` render pixel-identically to the original static page.
//! Both stylesheets ship in this repo under `assets/`; they are the rendering
//! contract, and the components are meaningless without them.
//!
//! Extracted from `developer.eona-x.eu` (`crates/eona-ds`), whose git history this
//! repo preserves. The components are renderer-agnostic: enable the `ssr` feature to
//! render them to HTML strings (how the portal uses them) or `csr` to mount them in a
//! browser/WASM host.

/// Design tokens — custom properties (colours, type scale, spacing) on `:root`.
/// Must be applied before [`COMPONENTS_CSS`], which consumes these variables.
pub const TOKENS_CSS: &str = include_str!("../assets/tokens.css");

/// Component styles, keyed to the class names the components emit.
/// Meaningless without [`TOKENS_CSS`].
pub const COMPONENTS_CSS: &str = include_str!("../assets/components.css");

/// Styles for the two presentational ontology components — [`crate::OntoBadge`]
/// and [`crate::OntoAnnotation`]. Consumes the same [`TOKENS_CSS`] custom
/// properties as [`COMPONENTS_CSS`], and is written against the themeable
/// `--eona-surface-*` / `--eona-text-*` layer so the pair follows `data-theme`
/// rather than pinning one appearance.
///
/// Held apart from [`COMPONENTS_CSS`] rather than folded into it: `ontology.css`
/// is a name three repositories already write out by hand (the portal's
/// `crates/site/src/main.rs`, `eona-vocabulary-ui`'s `build.rs`, and
/// `assets/demo-shell.html`), and folding it would break all three for no
/// rendering gain.
///
/// The browser's own classes (`.onto-iri`, `.term-*`, `.ontology-*`) left with
/// the stateful tier — see the `ontology` module's note.
pub const ONTOLOGY_CSS: &str = include_str!("../assets/ontology.css");

/// The EONA-X mark, as an SVG. Write it to `logo/logo-transparent.svg` relative to
/// the page.
///
/// A crate asset rather than the host's problem, because two things here cannot
/// render correctly without it: [`crate::SiteHeader`] hardcodes that path twice
/// (`src/organisms/site_header.rs:101,105`) and `assets/demo-shell.html` links it
/// as the favicon. A host that had to supply it got a header with a hole in it.
///
/// It is 264 KB — a generated wrapper whose actual payload is a 34 KB greyscale
/// mask — because these are the charter's own bytes. Re-authoring it smaller would
/// mean redrawing the mark, which is not this crate's call to make.
pub const LOGO_SVG: &str = include_str!("../assets/logo/logo-transparent.svg");

pub mod atoms;
pub mod demo;

/// One usage snippet per component, in Yew and in React, generated by
/// `cargo xtask bridgegen` from the same `abi/toolkit.abi.json` that types the
/// React package.
///
/// Compiled in from `bridge/` rather than living under `src/`: `src_hash` is
/// taken over `src/**/*.rs` (`xtask/src/parse.rs`), so a generated file inside
/// `src/` would be an input to the hash of the document describing it and
/// `cargo xtask check` would need two passes to converge.
///
/// [`crate::ComponentsGallery`] renders the whole table
/// (`src/organisms/components_gallery.rs:298`); the lookup stays at the call
/// site, never inside a component — see [`examples::snippet`].
#[path = "../bridge/examples.rs"]
pub mod examples;

pub mod molecules;

/// The two RDF/OWL model types [`crate::OntoBadge`] and
/// [`crate::OntoAnnotation`] are typed on.
///
/// This is all that is left of the module: the stateful ontology browser, the
/// rest of the model and the JSON-LD parser moved back to `eona-vocabulary-ui`,
/// its only consumer. These two stayed because they are prop types of two
/// components that stayed, and because they must be the *same* types on both
/// sides of the crate boundary — `eona-vocabulary-ui` re-exports them rather
/// than redefining them, or its `Term.kind` would no longer fit
/// `OntoBadgeProps::variant` (`src/atoms/onto_badge.rs:60`).
pub mod ontology;
pub mod organisms;

pub use atoms::*;
pub use molecules::*;
pub use organisms::*;
